version: "3.7"

services:
  piazza-api:
    build: .
    image: piazza-api:latest
    container_name: piazza-api
    restart: always
    ports:
      - 127.0.0.1:6006:8000
    env_file:
      - .env.prod
    networks:
      - mysql-network
    external_links:
      - mysql
    volumes:
      - /srv/piazza-api/media:/app/media
      - /srv/piazza-api/static:/app/static

networks:
  mysql-network:
    external: true