# Generated by Django 3.2.4 on 2021-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='موضوع'),
        ),
    ]
