# Generated by Django 3.2.4 on 2021-07-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
