# Generated by Django 3.2.4 on 2021-11-08 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='savedby',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ذخیره شده توسط: '),
        ),
    ]
