# Generated by Django 3.2.4 on 2021-07-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
    ]
