# Generated by Django 3.2.4 on 2021-07-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=2000, verbose_name='رمز عبور'),
        ),
    ]
