# Generated by Django 3.2.4 on 2021-11-08 04:11

import django.core.validators
from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_post_savedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, help_text='Image size should be less than 1.0\xa0MB', null=True, upload_to=master.models.post_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), master.models.validate_image_size], verbose_name='فایل'),
        ),
    ]
