# Generated by Django 3.2.4 on 2021-07-09 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, through='master.CourseStudent', to=settings.AUTH_USER_MODEL, verbose_name='دانشجویان'),
        ),
    ]
