# Generated by Django 3.2.4 on 2021-07-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_post_saved_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAnswer',
        ),
    ]
