# Generated by Django 3.2.4 on 2021-07-10 01:13

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=master.models.user_photo_directory_path, verbose_name='تصویر پروفایل'),
        ),
    ]
