# Generated by Django 3.2.4 on 2021-07-12 04:42

import django.core.validators
from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_delete_postanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, help_text='Image size should be less than 1.0\xa0MB', null=True, upload_to=master.models.exercise_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), master.models.validate_image_size], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='exerciseanswer',
            name='file',
            field=models.FileField(blank=True, help_text='Image size should be less than 1.0\xa0MB', null=True, upload_to=master.models.exercise_ans_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), master.models.validate_image_size], verbose_name='فایل'),
        ),
    ]
