# Generated by Django 3.2.4 on 2021-07-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
