# Generated by Django 3.2.4 on 2021-07-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20210710_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postanswer',
            options={'ordering': ['-date'], 'verbose_name': 'پاسخ استاد', 'verbose_name_plural': 'پاسخ های اساتید'},
        ),
    ]
