# Generated by Django 3.2.4 on 2021-07-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20210711_0148'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
